# This is a basic workflow that is manually triggered

name: Test python

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
      branches:
        - main 
        - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout v3
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4

    - name: Installing dependencies
      run: sudo apt install python3-pip | pip3 install pytest
      
    - name: Run test
      run: pytest test.py


   



  
